name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libgtest-dev
          cd /usr/src/gtest
          sudo cmake -S . -B build
          sudo cmake --build build
          sudo cp build/lib/*.a /usr/local/lib/


      - name: Build with Coverage Flags
        run: |          
          mkdir build
          cd build
          clang++ -fprofile-instr-generate -fcoverage-mapping \
            -I../lib ../src/*.cpp ../src/**/*.cpp -o app
          clang++ -fprofile-instr-generate -fcoverage-mapping \
            -I../lib ..I/src ../tests/utest-product.cpp -o tests -lgtest -lgtest_main -pthread


      - name: Run Tests (Generate .profraw)
        run: |
          cd build
          LLVM_PROFILE_FILE="coverage.profraw" ./app
          LLVM_PROFILE_FILE="tests.profraw" ./tests

      - name: Convert .profraw â†’ .profdata
        run: |
          cd build
          llvm-profdata merge -sparse coverage.profraw tests.profraw -o coverage.profdata

      - name: Generate HTML Coverage Report
        run: |
          cd build
          llvm-cov show ./app \
            -instr-profile=coverage.profdata \
            -format=html \
            -output-dir=coverage_html \
            -name=.*

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-cov-report
          path: build/coverage_html
