name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm


      - name: Build with Coverage Flags
        run: |         
          git clone https://github.com/google/googletest.git
          cmake -S googletest -B build -DCMAKE_CXX_COMPILER=clang++
          cmake --build build -j
          clang++ -fprofile-instr-generate -fcoverage-mapping \
            -Ilib src/*.cpp src/**/*.cpp -o app
          clang++ -fprofile-instr-generate -fcoverage-mapping \
          -Ilib -Igoogletest/googletest/include tests/utest-product.cpp -o tests -lgtest -lgtest_main -pthread
          ls


      - name: Run Tests (Generate .profraw)
        run: |
          LLVM_PROFILE_FILE="coverage.profraw" ./app
          LLVM_PROFILE_FILE="tests.profraw" ./tests

      - name: Convert .profraw â†’ .profdata
        run: |
          llvm-profdata merge -sparse coverage.profraw tests.profraw -o coverage.profdata

      - name: Generate HTML Coverage Report
        run: |
          llvm-cov show ./app \
            -instr-profile=coverage.profdata \
            -format=html \
            -output-dir=coverage_html \
            -name=.*

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-cov-report
          path: coverage_html
